# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentBrowser < Formula
  desc "Performant MCP aggregator"
  homepage "https://cobrowser.xyz"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/co-browser/agent-browser/releases/download/v1.1.0/agent-browser-v1.1.0-darwin-amd64.tar.gz"
      sha256 "9ad3194d14c8d40d38f1a4aa3dfab81e5df1684e0b8589a5d3e0248366c8c5f4"

      def install
        bin.install "agent-browser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/co-browser/agent-browser/releases/download/v1.1.0/agent-browser-v1.1.0-darwin-arm64.tar.gz"
      sha256 "55a9990c502fb2f58fdf391a37630a9f87ef65ea7f10188f598a74c3156cc309"

      def install
        bin.install "agent-browser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/co-browser/agent-browser/releases/download/v1.1.0/agent-browser-v1.1.0-linux-amd64.tar.gz"
        sha256 "bf4c383e7e0f4170201392cf6891e45e174ea16ad1c44c805f5dc3093b7a6652"

        def install
          bin.install "agent-browser"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/co-browser/agent-browser/releases/download/v1.1.0/agent-browser-v1.1.0-linux-arm64.tar.gz"
        sha256 "19c552023897f4443d822543d3cc9f6d5aaf15ae49b58a1dbe169d92e980e661"

        def install
          bin.install "agent-browser"
        end
      end
    end
  end
end
