# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentBrowser < Formula
  desc "a browser for agents"
  homepage "https://cobrowser.xyz"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/co-browser/agent-browser/releases/download/v1.0.0/agent-browser-v1.0.0-darwin-amd64.tar.gz"
      sha256 "490703522f2f1c157d82d3035442e701af9ce6aadc70e103891b840ccb425220"

      def install
        bin.install "agent-browser"
      end
    end
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/cobrowser-images/agent-browser-v1.0.0-darwin-arm64.tar.gz"
      sha256 "3fdfb6222af7cfb518d6dbae7126dd69b0fa44e0ff5fac2646867b9e9b3a480f"

      def install
        bin.install "agent-browser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/co-browser/agent-browser/releases/download/v1.0.0/agent-browser-v1.0.0-linux-amd64.tar.gz"
        sha256 "54365043eb5e138ebaf2ceec485784645d5bd3995e1f01e7e6d9d6499a218ccc"

        def install
          bin.install "agent-browser"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/co-browser/agent-browser/releases/download/v1.0.0/agent-browser-v1.0.0-linux-arm64.tar.gz"
        sha256 "2683999ee730b4b912a19b03037251018e767e4c91d8cc336f1973d5399add17"

        def install
          bin.install "agent-browser"
        end
      end
    end
  end
end
