# This file was generated by GoReleaser. DO NOT EDIT.
class Agentbrowser < Formula
  desc "agent-browser: a navigator for agents"
  homepage "https://github.com/co-browser/agent-browser"
  version "1.3.2"

  if OS.mac?
    url "https://github.com/co-browser/agent-browser/releases/download/v1.3.2/agent-browser-v1.3.2-darwin-amd64.tar.gz"
    sha256 "3078c6bf4de631b8356430d3fc8e917f2c39e35a0a04ce4db65ff6c54d716a51"
  elsif OS.linux?
    url "https://github.com/co-browser/agent-browser/releases/download/v1.3.2/agent-browser-v1.3.2-linux-amd64.tar.gz"
    sha256 "9aa9f8a19a68df141c135b7c2024e085faddf2395ab3336d6bb4292a78454d95"
  end

  def install
    bin.install "agent-browser"
    system "#{bin}/agent-browser"
  end
end
